### PR TITLE
Add snippets for Plant UML

### PR DESCRIPTION
**Pull request by trevershick**

### CODE REVIEW

**Comment by trevershick** [comment]
I don't know if you want to do snippets, or include this much. I figured I would get it started and others could add to the snippets. Any thoughts?

**Comment by plafue** [comment]
Give some time to review this - the other pull request were simple enough to test that they work correctly

**Comment by trevershick** [comment]
yeah of course.  Like I said, if you don't want to do large snippets like this, it's cool. I just decided to publish my snippets that I use.  I'm sure there are missing snippets.

**Comment by plafue** [comment]
It actually looks pretty nice, thanks so much for the pull request - i think i could make use of these myself!

**Comment by plafue** [comment]
@trevershick fyi: i just published the next minor with these changes. Cheers!

**Pull request merged**
